### ISSUE TITLE
Detect missing audio

### ISSUE THREAD

**Issue by chrusher** [dbvideostriketeam/wubloader#165]
It would be nice to have some way to detect which segments have missing audio and display in Thrimbletrimmer which segments are missing audio.

**Comment by ekimekim** [comment]
A more generalized solution for detecting "segments with issues" is to run a "validator" that checks segment size + ffprobe output and checks the values are within what we expect. Then we can look into flagged segments and work out if there's anything we can do, or even just so we can put a notice in the video like "yes we know the audio's bad".

**Comment by ekimekim** [comment]
This seems of limited value, we haven't had problems with bad segments (in ways we could detect) and this is 4 years old, I think it's not needed.
