### ISSUE TITLE
Image push access for PR builds

### ISSUE THREAD

**Issue by HubbeKing** [dbvideostriketeam/wubloader#238]
Currently, the GH Actions workflow I wrote runs on both PRs and pushes, but apparently it's not allowed to push images when running as a PR, despite the workflow requesting the right permission set for package writes.

There's probably something extra we have to do in order to allow package write from a PR, but fuck if I know what that is.

Gonna do a deep dive into the documentation at some point and see what might be up.

**Comment by HubbeKing** [comment]
This should be fixed by #246 but we can't really know until we make a new PR so nyeh

**Comment by ekimekim** [comment]
https://github.com/dbvideostriketeam/wubloader/pull/373 built successfully so I think this is completed.
