### ISSUE TITLE
Audit logging for thrimshim

### ISSUE THREAD

**Issue by ekimekim** [dbvideostriketeam/wubloader#293]
To help reconstruct what changes were made to a video and when

**Comment by chrusher** [comment]
Is this mostly changing the logging in thrimshim?

**Comment by ekimekim** [comment]
Application logs aren't structured or stored anywhere long term, ideally this would be a write to a database table for each change.
Something like: each time edits are submitted, the new edit inputs are written to a seperate table in a new row with a timestamp (multiple rows can exist for the same event, just with different timestamps).
