### ISSUE TITLE
Automate deployments of thumbnail templates 

### ISSUE THREAD

**Issue by chrusher** [dbvideostriketeam/wubloader#358]
It would be nice if the thumbnail templates could be updated on one node and the other edit nodes could automatically update. Existing `backfiller` code could be adapted but special handling will be need for when a template is updated rather than added.

**Comment by ekimekim** [comment]
Bonus work: Making it possible for non-technical folks to upload/update templates.

**Comment by ekimekim** [comment]
Thinking about it, it may be easier to store the templates in the database. They are not large, nor accessed frequently. In addition, thrimshim needs to know which ones exist and thrimshim is designed to not nessecarily have disk access. This solves the distribution problem (even for volunteer edit nodes), though we would need to make some tooling for template management. But we want to do that anyway, so non-technical folks can manage it.

**Comment by chrusher** [comment]
Yeah that seems like a reasonable solution.

For template management, we would want to add, replace, rename and delete templates as well as setting and modifying the template parameters and any template attribution (see issue #380). I assume a web form to do this should not be too difficult. We likely want to put authentication on the web form so only the art team and the wub wranglers can modify things.

**Comment by ekimekim** [comment]
An additional thought on this: Right now the default thumbnail template is selected via a hard-coded list inside thrimshim. This has already broken things once because we renamed the templates and didn't update thrimshim.
A better solution would probably be to make "default template for each shift" selectable in whatever UI we end up with.

This is a bonus though, our current solution does work.

**Comment by chrusher** [comment]
Simplest way to do that I would think is to have a `default_templates` table in the database that the wubloader wranglers could edit as needed. We could also have a `is_omega` flag we can flip when it reaches that part of the run.
