### ISSUE TITLE
Error running default docker-compose 

### ISSUE THREAD

**Issue by chrusher** [dbvideostriketeam/wubloader#359]
Running `generate-docker-compose` on the default `docker-compose.jsonnet` now gives `RUNTIME ERROR: undefined external variable: tag` which at the very least is not documented.

**Comment by ekimekim** [comment]
I can't reproduce this, and I'm not sure how it would be possible.

We define the tag when we run the docker-compose file:
```
```

**Comment by chrusher** [comment]
Ok this looks like I was running an old version of `generate-docker-compose`. I am going to close this issue.
