### ISSUE TITLE
Change Base Container to Speed Up Builds

### ISSUE THREAD

**Issue by chrusher** [dbvideostriketeam/wubloader#364]
Under Alpine Linux, most third party Python packages have to be built rather than installed from a wheel. Switching to an different base container image would greatly speed up building.

**Comment by dcollinsn** [comment]
This may be as simple as running `pip install --upgrade pip wheel` before attempting to install any other python packages.

**Comment by chrusher** [comment]
Ekim would know better but I believe it has something to do with the fact Alpine uses `musl` rather than `glibc` as its C standard library.

**Comment by ekimekim** [comment]
In theory there should be wheels for musl (depending on the package). Will try upgrading pip and see if it helps.

**Comment by ekimekim** [comment]
This seems to have done the trick - but we might want to change container base anyway.

**Comment by chrusher** [comment]
How difficult would it be to roll our own? Would there be any advantage to doing so?

**Comment by ekimekim** [comment]
It seems we got the thing we wanted out of this - changing base image isn't really important otherwise.
