### ISSUE TITLE
thumbnails: Allow combining frame with one-off uploaded template

### ISSUE THREAD

**Issue by ekimekim** [dbvideostriketeam/wubloader#366]
It is often the case that a custom one-off thumbnail is still made up of a "border" around the outside + a still frame from the video. In these cases it is annoying extra work to download a frame and essentially manually perform the templating process. But we also don't want to add the one-off as a template as this clutters up the templates list.

We should be able to accept a custom template image in thrimbletrimmer, which is then applied to the chosen frame to make a thumbnail.
This could be done without signifigant backend changes by implementing it in restreamer, having thrimbletrimmer download the image, then present it as a fully custom thumbnail when uploading. Or we could add a new `thumbnail_mode`, though this would mean a) needing to stash the templating parameters somewhere (in the template "name"?), b) putting the custom template in the thumbnail image column is a problem since this column *should* contain the generated image. We would probably instead want a new column.

**Comment by chrusher** [comment]
I think generating the template in the restreamer from thrimbletrimmer then treating it as a custom template is the better way.

**Comment by ekimekim** [comment]
Agreed. Are you taking this as part of the thumbnail work?

**Comment by chrusher** [comment]
Yes. I might as well do all the thumbnail work as one project.
