### ISSUE TITLE
Template cropping tool: "video frame with custom one-off overlay" doesn't work

### ISSUE THREAD

**Issue by dcollinsn** [dbvideostriketeam/wubloader#445]
We're unlikely to use this much/at all, but the "one-off overlay" option does not properly populate the template image on the right side of the cropping GUI. I'm not really sure how to do this because I don't really understand HTML upload stuff.

We should either hide the new advanced template options in the "one-off" mode, or figure out how to put the chosen image on the right side frame.

![image](https://github.com/user-attachments/assets/4e4f9194-db40-46c6-bbb8-caf87684ceeb)

**Comment by ekimekim** [comment]
Fixed by 3d22afb
