### ISSUE TITLE
Seperate Upload Location and Cut Type in Thrimbletrimmer

### ISSUE THREAD

**Issue by chrusher** [dbvideostriketeam/wubloader#446]
Currently upload locations and cut types are mixed together in the `Upload Location` dropdown in Advanced Submission Options. Upload location and cut types should be separate dropdowns.

**Comment by dcollinsn** [comment]
Dupe of #431?

**Comment by ekimekim** [comment]
Technically that's about the backend and this is UI for the same, but yes it should just be one issue.
