### ISSUE TITLE
Investigate performance of downloading thumbnail template images

### ISSUE THREAD

**Issue by dcollinsn** [dbvideostriketeam/wubloader#458]
Probably a "next year" at this point, but it takes me about 6 seconds to download a 100kB thumbnail template image like https://toodles.videostrike.team:1337/thrimshim/template/tech_test.png, and there are no response headers enabling client-side caching.

Oddly, downloads of a built thumbnail are fast(er). Accessing /thumbnail/desertbus/source.png takes one second for a composited image, when the template alone is extremely slow. Even if the issue is that the raw template data is stored as a database blob, there seems to be a problem here - if it takes 6 seconds to get the template from the database, it should take more than 6 seconds to serve a composite image that depends on that template.

I suspect that there's some bottleneck in the thrimshim/template image serving process. Is it normal to use `flask.Response` rather than `send_file`? https://github.com/dbvideostriketeam/wubloader/blob/master/thrimshim/thrimshim/main.py#L631

Even if there isn't, we could get significant UX gains by allowing some level of client-side caching.

**Comment by dcollinsn** [comment]
Datapoint: fiddling.png is 1.29MB and takes 56 seconds to download - about 10x on both counts compared to tech_test.png. I feel like the request is being streamed from the database to python to nginx in very small chunks, but I don't use flask or postgres so I'm not sure if there's some specific reason why that would be happening.


![image](https://github.com/user-attachments/assets/869934fb-d538-400e-9f12-49105748196f)

**Comment by chrusher** [comment]
I feel like this is in ekim's wheelhouse. While I did write the thumbnail template backend I am no expert in web stuff. Using `Response` in `thrimshim` for the templates was based on similar code in the `restreamer`.

**Comment by ekimekim** [comment]
Definitely something odd there, will need to experiment when I can. Buffering the whole response shouldn't be the issue, since as you say it's faster when compositing which does the same thing.
