### ISSUE TITLE
chat_archiver_1 errors - gethostbyname() argument 1 must be str, bytes or bytearray, not None

### ISSUE THREAD

**Issue by dcollinsn** [dbvideostriketeam/wubloader#474]
On 5019b25, scanning through various error logs, I'm getting errors that it is failing to get the "url" `/2024/participate/challenge`:

> chat_archiver_1     | [2024-11-09 09:29:38,021]     INFO root(main:463): All batches are merged
> chat_archiver_1     | Traceback (most recent call last):
> chat_archiver_1     |   File "/usr/lib/python3.9/site-packages/gevent/threadpool.py", line 173, in __run_task
> chat_archiver_1     |     thread_result.set(func(*args, **kwargs))
> chat_archiver_1     | TypeError: gethostbyname() argument 1 must be str, bytes or bytearray, not None
> chat_archiver_1     | 2024-11-09T09:29:39Z (<ThreadPoolWorker at 0x79b53388c080 thread_ident=0x79b532e09b38 threadpool-hub=<Hub at 0x79b5342dd770 thread_ident=0x79b5361abb48>>, <built-in function gethostbyname>) failed with TypeError
> chat_archiver_1     |
> chat_archiver_1     | Traceback (most recent call last):
> chat_archiver_1     |   File "/usr/lib/python3.9/site-packages/gevent/threadpool.py", line 173, in __run_task
> chat_archiver_1     |     thread_result.set(func(*args, **kwargs))
> chat_archiver_1     | TypeError: gethostbyname() argument 1 must be str, bytes or bytearray, not None
> chat_archiver_1     | 2024-11-09T09:29:39Z (<ThreadPoolWorker at 0x79b53388c080 thread_ident=0x79b532e09b38 threadpool-hub=<Hub at 0x79b5342dd770 thread_ident=0x79b5361abb48>>, <built-in function gethostbyname>) failed with TypeError
> chat_archiver_1     |
> chat_archiver_1     | Traceback (most recent call last):
> chat_archiver_1     |   File "/usr/lib/python3.9/site-packages/gevent/threadpool.py", line 173, in __run_task
> chat_archiver_1     |     thread_result.set(func(*args, **kwargs))
> chat_archiver_1     | TypeError: gethostbyname() argument 1 must be str, bytes or bytearray, not None
> chat_archiver_1     | 2024-11-09T09:29:40Z (<ThreadPoolWorker at 0x79b53388c080 thread_ident=0x79b532e09b38 threadpool-hub=<Hub at 0x79b5342dd770 thread_ident=0x79b5361abb48>>, <built-in function gethostbyname>) failed with TypeError
> chat_archiver_1     |
> chat_archiver_1     | [2024-11-09 09:29:40,980]  WARNING root(main:406): Unable to fetch link https://desertbus.org/participate/challenge
> chat_archiver_1     | Traceback (most recent call last):
> chat_archiver_1     |   File "/usr/lib/python3.9/site-packages/chat_archiver/main.py", line 388, in get_url
> chat_archiver_1     |     download_media(url, media_dir)
> chat_archiver_1     |   File "/usr/lib/python3.9/site-packages/common/stats.py", line 172, in wrapper
> chat_archiver_1     |     raise error from None # re-raise error with original traceback
> chat_archiver_1     |   File "/usr/lib/python3.9/site-packages/common/stats.py", line 135, in wrapper
> chat_archiver_1     |     ret = fn(*args, **kwargs)
> chat_archiver_1     |   File "/usr/lib/python3.9/site-packages/common/media.py", line 128, in download_media
> chat_archiver_1     |     raise Exception(f"All retries failed for url {urls[-1]}: {errors}")
> chat_archiver_1     | Exception: All retries failed for url /2024/participate/challenge: [TypeError('gethostbyname() argument 1 must be str, bytes or bytearray, not None'), TypeError('gethostbyname() argument 1 must be str, bytes or bytearray, not None'), TypeError('gethostbyname() argument 1 must be str, bytes or bytearray, not None')]
> chat_archiver_1     | [2024-11-09 09:29:49,907]     INFO root(main:402): Ignoring non-media link https://bit.ly/DB-Challenges: Disallowed content-type text/html for url https://desertbus.org/2024/?id=672e5bff047f4e0001d0f230
> chat_archiver_1     | [2024-11-09 09:30:00,001]     INFO root(main:435): Wrote batch /mnt/desertbus/chat/2024-11-09T09/28:00-uBghDeZr661jGGzUVm-OfesfzznWbDaEv2TyEuIcVC8.json
> chat_archiver_1     | [2024-11-09 09:30:18,018]     INFO root(main:402): Ignoring non-media link https://videostrike.team/DB18/: Disallowed content-type text/html; charset=UTF-8 for url https://videostrike.team/DB18/
> chat_archiver_1     | Traceback (most recent call last):
> chat_archiver_1     |   File "/usr/lib/python3.9/site-packages/gevent/threadpool.py", line 173, in __run_task
> chat_archiver_1     |     thread_result.set(func(*args, **kwargs))
> chat_archiver_1     | TypeError: gethostbyname() argument 1 must be str, bytes or bytearray, not None

**Comment by dcollinsn** [comment]
Hypothesis, when someone posts https://desertbus.org/participate/challenge in chat, the archiver follows the link to see if it's an image. That URL redirects to `/2024/participate/challenge` (without a hostname), so urllib may be returning that here https://github.com/dbvideostriketeam/wubloader/blob/master/common/common/media.py#L114C6-L114C44 leading to a non-url being treated as a url. 

Just logspam, since there's no media to download at that URL anyway.

**Comment by dcollinsn** [comment]
I have another example of this which appears to be related to an actual media download, from flickr:

> chat_archiver_1     | [2024-11-09 07:12:37,911]     INFO root(main:463): All batches are merged
> chat_archiver_1     | [2024-11-09 07:12:39,569]     INFO root(main:402): Ignoring non-media link https://www.youtube.com/watch?v=BRFFM8bNiJg: Disallowed content-type text/html; charset=utf-8 for url https://www.youtube.com/watch?v=BRFFM8bNiJg
> chat_archiver_1     | [2024-11-09 07:12:53,784]     INFO root(media:181): Downloaded file for https://i.imgur.com/e0BQI7b.jpeg
> chat_archiver_1     | [2024-11-09 07:13:00,003]     INFO root(main:435): Wrote batch /mnt/desertbus/chat/2024-11-09T07/11:00-tMhbEijwWAzmBExUbap-K99twq79yZ8WQ4GcUSeKDIs.json
> chat_archiver_1     | Traceback (most recent call last):
> chat_archiver_1     |   File "/usr/lib/python3.9/site-packages/gevent/threadpool.py", line 173, in __run_task
> chat_archiver_1     |     thread_result.set(func(*args, **kwargs))
> chat_archiver_1     | TypeError: gethostbyname() argument 1 must be str, bytes or bytearray, not None
> chat_archiver_1     | 2024-11-09T07:13:17Z (<ThreadPoolWorker at 0x79b5335d08c0 thread_ident=0x79b533033b38 threadpool-hub=<Hub at 0x79b5342dd770 thread_ident=0x79b5361abb48>>, <built-in function gethostbyname>) failed with TypeError
> chat_archiver_1     |
> chat_archiver_1     | [2024-11-09 07:13:17,230]     INFO root(media:181): Downloaded file for https://i.imgur.com/xH17HLG.jpeg
> chat_archiver_1     | Traceback (most recent call last):
> chat_archiver_1     |   File "/usr/lib/python3.9/site-packages/gevent/threadpool.py", line 173, in __run_task
> chat_archiver_1     |     thread_result.set(func(*args, **kwargs))
> chat_archiver_1     | TypeError: gethostbyname() argument 1 must be str, bytes or bytearray, not None
> chat_archiver_1     | 2024-11-09T07:13:18Z (<ThreadPoolWorker at 0x79b5335d08c0 thread_ident=0x79b533033b38 threadpool-hub=<Hub at 0x79b5342dd770 thread_ident=0x79b5361abb48>>, <built-in function gethostbyname>) failed with TypeError
> chat_archiver_1     |
> chat_archiver_1     | Traceback (most recent call last):
> chat_archiver_1     |   File "/usr/lib/python3.9/site-packages/gevent/threadpool.py", line 173, in __run_task
> chat_archiver_1     |     thread_result.set(func(*args, **kwargs))
> chat_archiver_1     | TypeError: gethostbyname() argument 1 must be str, bytes or bytearray, not None
> chat_archiver_1     | 2024-11-09T07:13:19Z (<ThreadPoolWorker at 0x79b5335d08c0 thread_ident=0x79b533033b38 threadpool-hub=<Hub at 0x79b5342dd770 thread_ident=0x79b5361abb48>>, <built-in function gethostbyname>) failed with TypeError
> chat_archiver_1     |
> chat_archiver_1     | [2024-11-09 07:13:19,210]  WARNING root(main:406): Unable to fetch link https://flic.kr/p/2qt3zDb
> chat_archiver_1     | Traceback (most recent call last):
> chat_archiver_1     |   File "/usr/lib/python3.9/site-packages/chat_archiver/main.py", line 388, in get_url
> chat_archiver_1     |     download_media(url, media_dir)
> chat_archiver_1     |   File "/usr/lib/python3.9/site-packages/common/stats.py", line 172, in wrapper
> chat_archiver_1     |     raise error from None # re-raise error with original traceback
> chat_archiver_1     |   File "/usr/lib/python3.9/site-packages/common/stats.py", line 135, in wrapper
> chat_archiver_1     |     ret = fn(*args, **kwargs)
> chat_archiver_1     |   File "/usr/lib/python3.9/site-packages/common/media.py", line 128, in download_media
> chat_archiver_1     |     raise Exception(f"All retries failed for url {urls[-1]}: {errors}")
> chat_archiver_1     | Exception: All retries failed for url /photo.gne?rb=1&short=2qt3zDb: [TypeError('gethostbyname() argument 1 must be str, bytes or bytearray, not None'), TypeError('gethostbyname() argument 1 must be str, bytes or bytearray, not None'), TypeError('gethostbyname() argument 1 must be str, bytes or bytearray, not None')]

It is failing to follow a redirect from `https://flic.kr/p/2qt3zDb`

**Comment by dcollinsn** [comment]
Not sure if this is the same or not, similar error but this one does have a hostname in the exception (gyazo.com):

> chat_archiver_1     | [2024-11-09 07:13:42,332]  WARNING root(main:406): Unable to fetch link gyazo.com/collections/214f3c8d637893c13fcb411012307aea
> chat_archiver_1     | Traceback (most recent call last):
> chat_archiver_1     |   File "/usr/lib/python3.9/site-packages/chat_archiver/main.py", line 388, in get_url
> chat_archiver_1     |     download_media(url, media_dir)
> chat_archiver_1     |   File "/usr/lib/python3.9/site-packages/common/stats.py", line 172, in wrapper
> chat_archiver_1     |     raise error from None # re-raise error with original traceback
> chat_archiver_1     |   File "/usr/lib/python3.9/site-packages/common/stats.py", line 135, in wrapper
> chat_archiver_1     |     ret = fn(*args, **kwargs)
> chat_archiver_1     |   File "/usr/lib/python3.9/site-packages/common/media.py", line 128, in download_media
> chat_archiver_1     |     raise Exception(f"All retries failed for url {urls[-1]}: {errors}")
> chat_archiver_1     | Exception: All retries failed for url gyazo.com/collections/214f3c8d637893c13fcb411012307aea: [TypeError('gethostbyname() argument 1 must be str, bytes or bytearray, not None'), TypeError('gethostbyname() argument 1 must be str, bytes or bytearray, not None'), TypeError('gethostbyname() argument 1 must be str, bytes or bytearray, not None')]

**Comment by HubbeKing** [comment]
Should be fixed as of https://github.com/dbvideostriketeam/wubloader/commit/9d45833ed189da9845e87c0a5486ccdfc8c682f6
