### ISSUE TITLE
Prizebot uses relative rather than absolute URLs for prize links

### ISSUE THREAD

**Issue by dcollinsn** [dbvideostriketeam/wubloader#485]
This link should go to desertbus.org:

![image](https://github.com/user-attachments/assets/28e2bd14-b388-4ef3-be08-337f30514e8e)

PrizeBot grabs this link here: https://github.com/dbvideostriketeam/wubloader/blob/master/zulip_bots/zulip_bots/prizebot.py#L24-L56 and prints it here https://github.com/dbvideostriketeam/wubloader/blob/master/zulip_bots/zulip_bots/prizebot.py#L61 without adding the domain to the URL.

**Comment by ekimekim** [comment]
fixed 5012c2c
